### ISSUE TITLE
Recreate app logic in JRuby

### ISSUE THREAD

**Issue by edubkendo** [rsense/rsense#4]
- [x] [Daemonize](https://github.com/rsense/rsense/issues/11)
- [x] [Code completion](https://github.com/rsense/rsense/issues/6)
- [ ]  [Find definition](https://github.com/rsense/rsense/issues/7)
- [ ]  [Type inference](https://github.com/rsense/rsense/issues/8)
- [ ]  [Where/Testing/Tools building on top](https://github.com/rsense/rsense/issues/9)
- [x] [JSON server architecture](https://github.com/rsense/rsense/issues/10)
- [x] [Much smarter about loading projects/files/etc](https://github.com/rsense/rsense/issues/5)
